


FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

COPY *.csproj .
RUN dotnet restore

COPY ./. .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS build
WORKDIR /app

COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "PAYMENT.dll"]



